version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mini-twitter.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "3002:80"
    depends_on:
      - postgres
